### ISSUE TITLE
Support for Mavericks (OS X 10.9)?

### ISSUE THREAD

**Issue by mklb** [JadenGeller/Helium#17]
Is it possible to support OS X 10.9?

**Comment by rkk** [comment]
+1 on that.

**Comment by JadenGeller** [comment]
I recently updated the app from using WebView (OS X 10.2) to WKWebView (OS X 10.10), which breaks compatibility for OS X 10.9. It'd most likely be trivial to create a branch and revert it the the commit before I made this change and have it run on OS X 10.9, but there will not be support of 10.9 in the release branch due to the recency of WKWebView and the disdain of using the nearly deprecated WebView instead.

**Comment by mklb** [comment]
I see.. 
I would love to do that but I can´t get to run SWIFT in Xcode (for OSX) on my "old" machine. Thank you anyway ;)

**Comment by janoskk** [comment]
+1
I think there are still many people using Mavericks. Please consider to have parallel development for WebView and WKWebView, or at least provide the last stable binary for Mavericks. Thank you anyway ;-)

**Comment by MartyLake** [comment]
+1 for last stable Mavericks =)

**Comment by jaflo** [comment]
I am currently trying to recompile from d2b2bbb4e79de3200358920ea4a38ab6dd3bc435, the last version before WKWebView was introduced. I fixed all errors, but I am running into an issue:

> The document "Main.storyboard" could not be opened. OS X 10.10 or higher is required.

Is there any way anyone could provide the storyboard from a lower OS?

**Comment by nunoh** [comment]
+1 here too

**Comment by JadenGeller** [comment]
What version of Xcode do you have?

**Comment by jaflo** [comment]
@JadenGeller 6.2. To install 6.3 I would need to update to 10.10 (Currently on 10.9.5 and staying).

**Comment by ialexryan** [comment]
I just opened the Main.storyboard file in a text editor and deleted the `toolsVersion=XXXX` and `systemVersion=XXXX` from line 2.

I opened it in Xcode 6.3 and viewing the storyboard worked fine and it compiled fine, and the required version of Xcode had been reset to 4.6 or something. Try mucking around with those options.

**Comment by jaflo** [comment]
I removed `toolsVersion="..."`, `systemVersion="..."`, and `
        <plugIn identifier="com.apple.InterfaceBuilder.CocoaPlugin" version="..."/>
        <plugIn identifier="com.apple.WebKitIBPlugin" version="..."/>`but still cannot compile.

**Comment by fastzhong** [comment]
+1, please support 10.9.

**Comment by dasmurphy** [comment]
+1, any news on support for 10.9?

**Comment by JadenGeller** [comment]
I haven't gotten around to it yet, unfortunately. It'll probably be a few months to be honest since I won't be out of school until then.

**Comment by muuuh** [comment]
Can this topic be opened again please?

**Comment by JadenGeller** [comment]
Sure.

**Comment by albertobissacco** [comment]
+1

**Comment by mustii82** [comment]
+1 Please I need Mavericks support !!!

**Comment by mizterp** [comment]
A great alternative is the "Picture in Picture Viewer" Chrome extension

**Comment by mustii82** [comment]
chrome kill my battery life  on my MacBook i can't use it at this time :/

**Comment by Enterpreneur** [comment]
Can someone just upload the last working version for 10.9 (if it currently works)? I don't care about future support. Btw +1

**Comment by jalovcan** [comment]
+1
I would love to have it on Mavericks, could you please upload the version which works on it??

Thank you!!

**Comment by ialexryan** [comment]
Closing this issue because Mavericks came out in 2013 and was superseded by Yosemite in 2014. We're now four years and four versions of OS X past it, and it's time to move on.

That said, it's not hard to look through the [Releases](https://github.com/JadenGeller/Helium/releases) and find the last binary upload before [the commit that introduced WKWebView](https://github.com/JadenGeller/Helium/commit/bdd5b230481638c9ee602f1a3605cca46e74f79e), which appears to be [version 1.3](https://github.com/JadenGeller/Helium/releases/tag/1.3). YMMV.
