### ISSUE TITLE
REQ: Show on only 1 desktop

### ISSUE THREAD

**Issue by proactivematter** [JadenGeller/Helium#240]
Hello!

I have different desktops for different uses. It would be awesome to be able to have the option of showing on only 1 desktop instead of all desktops.

Thank you.

**Comment by slashlos** [comment]
Pretty sure this has always been there: in v2 it was here:

![Screen Shot 2020-01-20 at 10 16 35 AM](https://user-images.githubusercontent.com/3155005/72737702-0edc9580-3b6e-11ea-98c8-a16e3b76b51d.png)

On my fork [here](https://github.com/slashlos/Helium), we feature 2 distinct kinds of 'floats':
* over all spaces - default is yes (disable otherwise)
* over all full-screen apps (on its space)

![Screen Shot 2020-01-20 at 10 20 35 AM](https://user-images.githubusercontent.com/3155005/72738017-aa6e0600-3b6e-11ea-875f-15a6b3f0fd3a.png)

See Appearance under Windows menu, a Helium can be selected float above all spaces or disabled to it's limited to its current space - disable so you can then drag it around.  You can also float above the screen, and any full-screen apps, on its space.
