### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by JadenGeller** [JadenGeller/Helium#47]

**Comment by ryh** [comment]
If you want keep it small and fast, maybe no analytics functions embedded

**Comment by JadenGeller** [comment]
I was thinking it might be interesting to track what how many people use the app. Not sure if this will be implemented or not though. There are no plans to track the sites people visit obviously.

**Comment by Zegnat** [comment]
Phoning home with information is always tempting, but seldom necessary.

For such a single purpose app I don’t think it is worth tracking usage. Since tracking what websites are being displayed is a pretty big red flag there is little else you could track, right? Position on screens and window size maybe?

Instead you could advertise the number one statistic everyone is interested in: number of downloads. Maybe a download analytics page [like Minimal Status Bar has](http://visnup.github.io/Minimal-Status-Bar/downloads) ([source](https://github.com/visnup/Minimal-Status-Bar/blob/gh-pages/downloads.html))?

**Comment by JadenGeller** [comment]
That's exactly what I meant. I wanted usage analytics (aka how many users we have). That's really all I was considering. Might not be worth the effort though.

**Comment by Zegnat** [comment]
> That’s exactly what I meant. 

Sorry for jumping to other conclusions. I think it was triggered by the first comment talking about embedding functions.

> Might not be worth the effort though.

It is something that might look good on the page. Maybe just a total number of downloads? If you are not going for charts like MSB did the code becomes really easy. Here is a JSBin I whipped up: [total number of Helium downloads](http://jsbin.com/katejufuka/1/edit?html,js,output).

**Comment by JadenGeller** [comment]
That's fantastic! Exactly what I wanted! :D I'll add it to the site :)
